name: turistguide CI test

on:
  push:
    branches:
      - database
  pull_request:   # k칮rer ogs친 n친r man laver PR
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # 游댳 Build + run tests (unit + integration)
      - name: Build with Maven
        run: mvn clean verify --batch-mode

      # 游댳 Upload test results (s친 man kan se dem p친 GitHub)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      # 游댳 Qodana statisk analyse
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          results-dir: qodana-report

      # 游댳 Gem Qodana rapport som artefakt
      - name: Upload Qodana report
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana-report

      # 游댳 Upload artifact til deploy-job
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tourist-guide-jms-gr4'
          slot-name: 'Production'
          package: '*.jar'
